### Create a recipe page on Instacart
POST {{INSTACART_API_URI}}/idp/v1/products/recipe
Accept: application/json
Authorization: Bearer {{INSTACART_API_KEY}}
Content-Type: application/json

{
  "title": "Small Chocolate Cake (6 inches)",
  "image_url": "https://d3s8tbcesxr4jm.cloudfront.net/recipe-images/v3/small-chocolate-cake-6-inches/0_medium.jpg",
  "link_type": "recipe",
  "instructions": [
    "Preheat the oven to 350 degrees F and grease a 6-inch round cake pan.",
    "In a large bowl, combine flour, sugar, cocoa, baking powder, baking soda, salt, and cinnamon.",
    "Add egg, milk, oil, and vanilla to dry ingredients and mix well."
  ],
  "ingredients": [
    {
      "name": "whole milk",
      "display_text": "Whole milk",
      "measurements": [
        {
          "quantity": 0.5,
          "unit": "cup"
        }
      ]
    },
    {
      "name": "egg",
      "display_text": "Eggs",
      "measurements": [
        {
          "quantity": 1,
          "unit": "large"
        }
      ]
    },
    {
      "name": "ground cinnamon",
      "display_text": "Ground cinnamon",
      "measurements": [
        {
          "quantity": 0.55,
          "unit": "teaspoon"
        }
      ]
    }
  ],
  "landing_page_configuration": {
    "partner_linkback_url": "string",
    "enable_pantry_items": true
  }
}

