name: Trigger Amplify Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Tests have been moved to Amplify's build process
  trigger-amplify:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Trigger Amplify build for main
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST -d {} "https://webhooks.amplify.us-east-2.amazonaws.com/prod/webhooks?id=754957aa-15f4-414e-98ef-07ce05c50a27&token=y5GAuxZQdQoyuaAED9EKjAuyE0GlAaKvHxuOO1MZbE&operation=startbuild" -H "Content-Type:application/json"
      
      - name: Trigger Amplify build for develop
        if: github.ref == 'refs/heads/develop'
        run: |
          curl -X POST -d {} "https://webhooks.amplify.us-east-2.amazonaws.com/prod/webhooks?id=d3d2d34a-66e2-4226-9d82-f8a46c919177&token=grTNDRdevVryWsuFRHQTUI3qRoFKzRJjWmy7YmSKR8&operation=startbuild" -H "Content-Type:application/json"